const ADD_TICKET = "ADD_TICKET";
const UPDATE_TICKET = "UPDATE_TICKET";
const DELETE_TICKET = "DELETE_TICKET";
const SET_EDITING_TICKET = "SET_EDITING_TICKET";
const CLEAR_EDITING_TICKET = "CLEAR_EDITING_TICKET";

export {
  ADD_TICKET,
  UPDATE_TICKET,
  DELETE_TICKET,
  SET_EDITING_TICKET,
  CLEAR_EDITING_TICKET,
};
