const ADD_TICKET = "ADD_TICKET";
const UPDATE_TICKET = "UPDATE_TICKET";
const DELETE_TICKET = "DELETE_TICKET";
const SET_EDITING_TICKET = "SET_EDITING_TICKET";
const CLEAR_EDITING_TICKET = "CLEAR_EDITING_TICKET";
const SET_SORTING = "SET_SORTING";

const High_To_Low = "High to Low";
const Low_To_High = "Low to High";

export {
  ADD_TICKET,
  UPDATE_TICKET,
  DELETE_TICKET,
  SET_EDITING_TICKET,
  CLEAR_EDITING_TICKET,
  SET_SORTING,
  High_To_Low,
  Low_To_High,
};
